# Breeze colorscheme
# Normal colors
[colors.normal]
black = '#232627'
red = '#ed1515'
green = '#11d116'
yellow = '#fdbc4b'
blue = '#1d99f3'
magenta = '#9b59b6'
cyan = '#1abc9c'
white = '#fcfcfc'

# Bright colors
[colors.bright]
black = '#7f8c8d'
red = '#c0392b'
green = '#1cdc9a'
yellow = '#fdbc4b'
blue = '#3daee9'
magenta = '#8e44ad'
cyan = '#16a085'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#31363b'
red = '#783228'
green = '#17a262'
yellow = '#b65619'
blue = '#1b668f'
magenta = '#614a73'
cyan = '#186c60'
white = '#63686d'

[colors.primary]
background = "#011627"
foreground = "#c5c8c6"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 17

[font.normal]
family = "MesloLGSDZ Nerd Font Mono"

[font.bold]
family = "MesloLGSDZ Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGSDZ Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "MesloLGSDZ Nerd Font Mono"
style = "Bold Italic"


[[keyboard.bindings]]
chars = "\u001B[46;5u"
key = "Period"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[44;5u"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[61;5u"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[43;5u"
key = "Equals"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[59;5u"
key = "Semicolon"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[124;5u"
key = "Backslash"
mods = "Control|Shift"

[mouse]
hide_when_typing = false

[scrolling]
history = 1000

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.padding]
# x = 2
y = 2
